name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Build and test

    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Setup prisma
        run: pnpm turbo db:generate

      - name: Build
        run: pnpm build

      # - name: Test
      #   run: pnpm test
